"""empty message

Revision ID: 839cacdc7fde
Revises: b3bc06079204
Create Date: 2023-03-21 12:31:35.095729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839cacdc7fde'
down_revision = 'b3bc06079204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.Text(), nullable=False))
        batch_op.create_foreign_key("user_name", 'user', ['user_name'], ['first_name'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.Text(), nullable=False))
        batch_op.create_foreign_key("user_name", 'user', ['user_name'], ['first_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
