"""empty message

Revision ID: 9bbed8b97302
Revises: 82372092fe0a
Create Date: 2023-04-23 15:58:39.255341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbed8b97302'
down_revision = '82372092fe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('file_type', sa.Text(), nullable=True))
        batch_op.create_foreign_key("author_id", 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_type')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
